//! ADS-B Simulator - see README.md
//
// © NewForester, 2018.  Available under MIT licence terms.
//
//! The msg66 module implements the _mavlink message trait_ for the
//! MAVLink 'datastream request' message (id 66).
//!
//! Only message serialise is actually implemented
//! as the ADS-B Simulator need only generate this message.
//!
//! No getter/setter functions are implemented:  the message is 'obsolete'
//! but is still generated by the ADS-B device being simulated.
//!
use std::io::{Error, ErrorKind};

use mavlink;
use mavlink::byteorder::{WriteBytesExt};

// ---------------------------------------------------------------------

/*
 * MAVLink 66 'datastream request' message (obsolete but still comes in)
 */

const MSGLEN: usize = msglen!(6);

pub struct Message {
    buffy: [u8; MSGLEN],
}

impl Message {
    pub fn new() -> Message {
        Message {
            buffy: [0; MSGLEN],
        }
    }
}

impl mavlink::Message for Message {
    const MSGID: u8 = 66;
    const EXTRA: u8 = 0x94;
    const PAYLEN: usize = paylen!(MSGLEN);

    fn dump(&self) -> &Self {
        Self::dump_message (&self.buffy);

        self
    }

    fn message(&mut self) -> &mut [u8] {
        &mut self.buffy
    }

    fn pack_payload(&self, buffy: &mut Vec<u8>) -> Result<(),Error> {
        for _ii in 0..MSGLEN {
            buffy.write_u8(0)?;
        }

        Ok(())
    }

    fn unpack_payload(&mut self) -> Result<(),Error> {
        Err(Error::new(ErrorKind::Other, "Not implemented"))
    }
}

// EOF
